### ISSUE TITLE
Datastore fails when saving entity with null attribute value

### ISSUE THREAD

**Issue by toboid** [GoogleCloudPlatform/gcloud-node#1022]
When trying to save an object that has null property values `gcloud-node` errors:

``` javascript
dataset.insert({
  key: dataset.key('Test'),
  data: { foo: 'bar', baz: null }
}, err => {
  if (err) return console.log(err);
});
```
prints:
>Error: Unsupported field value, null, is provided.

I can see that the definition for `Value` in the [Datastore proto buffers api](https://github.com/GoogleCloudPlatform/google-cloud-datastore/blob/v1beta2-rev1-3.0.2/proto/datastore_v1.proto#L99) does not provide for null values. The [Ruby](https://github.com/blowmage/gcloud-ruby/blob/master/lib/gcloud/datastore/proto.rb#L67) and [Python](https://github.com/lucemia/gcloud-python/blob/master/gcloud/datastore/helpers.py#L261) clients create a message with no value attribute, is this an option for `gcloud-node`? I'd be really pleased to take a look at this if you'll take a pull request?

**Comment by stephenplusplus** [comment]
Definitely, that would be very welcome!

// @pcostell - makes sense, right?

**Comment by pcostell** [comment]
Makes sense to me. Can we make sure this gets updated for the v1beta3 branch as well? In particular the next version of the API includes NullValue as an explicit field: https://github.com/google/googleapis/blob/master/google/datastore/v1beta3/entity.proto#L119

**Comment by toboid** [comment]
OK great. Correctly saving the Null to datastore is straightforward, however the value comes back out as an empty array because [this](propertyToValue) function isn't able to distinguish between a property representing an empty array is currently indistinguishable from a property representing a null value since they have the exact same structure:

``` javascript
{
  "key": {
    ...
  },
  "property": [
    {
      "name": "i-am-a-null",
      "value": {
        "boolean_value": null,
        "integer_value": null,
        "double_value": null,
        "timestamp_microseconds_value": null,
        "key_value": null,
        "blob_key_value": null,
        "string_value": null,
        "blob_value": null,
        "entity_value": null,
        "list_value": [],
        "meaning": null,
        "indexed": true
      }
    },
    {
      "name": "i-am-an-empty-array",
      "value": {
        "boolean_value": null,
        "integer_value": null,
        "double_value": null,
        "timestamp_microseconds_value": null,
        "key_value": null,
        "blob_key_value": null,
        "string_value": null,
        "blob_value": null,
        "entity_value": null,
        "list_value": [],
        "meaning": null,
        "indexed": true
      }
    }
  ]
}
```
I'm still looking into how to handle this, do you have any suggestions? Should be easier for the v1beta3 branch.

**Comment by stephenplusplus** [comment]
That makes for a tricky problem, indeed. Can we glean any insight into handling this from the other client libraries?

**Comment by stephenplusplus** [comment]
@pcostell added nullValue support to the v1beta3 PR :+1:

**Comment by mcfarljw** [comment]
I'm also finding it a bit quirky to deal with nulls being returned as empty arrays.

**Comment by toboid** [comment]
I have the changes to correctly store null values [here](https://github.com/toboid/gcloud-node/commit/e714082bed0bf90e2a9248aee7c733541a930c22) but still can't see a solution for getting them back out correctly at the moment

**Comment by pcostell** [comment]
The Google versions of protobuf support this using the `hasField` method, which allows querying for whether a field has been explicitly set or not. There is an [issue](https://github.com/dcodeIO/protobuf.js/issues/200) in the protobufjs issue tracker for this.

As mentioned above, this is fixed in v1beta3 (mostly because v1beta3 uses `proto3`, where unset and the default value are considered the same thing).

**Comment by stephenplusplus** [comment]
Let's just wait for v1beta3 to have official support for this. It sounds like it's quite a hassle to support it now and v1beta3 is on the horizon. Support is ready in my v1beta3 PR, so I'm going to close the issue, but please re-open if there's something we can do to support it now.

**Comment by toboid** [comment]
Makes sense, I can't see a non-hacky way to correctly retrieve nulls at the moment.

**Comment by krisnye** [comment]
I have a fork which adds support for writing null values to the datastore today via a trivial fix.  It does NOT fix the problem with reading them as empty arrays. (Not a problem for my use case.)

https://github.com/krisnye/gcloud-node
