### ISSUE TITLE
Support setting an origin when using resumable upload

### ISSUE THREAD

**Issue by stephenplusplus** [GoogleCloudPlatform/gcloud-node#1099]
Related:
- https://github.com/GoogleCloudPlatform/gcloud-node/issues/818#issuecomment-178124099
- https://github.com/stephenplusplus/gcs-resumable-upload/issues/6

This will include a breaking change.

```js
// Before
file.createResumableUpload(metadata, callback);

// After
var options = {
  metadata: {},
  origin: '*'
};

file.createResumableUpload(options, callback);
```

**Comment by stephenplusplus** [comment]
@gotmikhail - pulling you over here so you can track this.

I released gcs-resumable-upload@0.4.0 with support for an `origin` option: https://github.com/stephenplusplus/gcs-resumable-upload/commit/8f961676fd7c3a7afef8a9707c8b7fbb9c15138e. So, that's available to use immediately until it makes it into gcloud-node.

**Comment by gotmikhail** [comment]
Here's what I've implemented:

```
var uploadConfig = {
    origin: '*',
    metadata: metadata,
    file: targetFile,
    bucket: targetBucket,
    authConfig: {
        keyFilename: sails.config.storage.cloudStorage.keyfile
    }
};
gcloudUpload.createURI(uploadConfig, function (err, uri) {
...
});
```
But, still getting `No 'Access-Control-Allow-Origin' header` on the client. Any thoughts on what I'm doing wrong?

**Comment by stephenplusplus** [comment]
@janesconference I'm sorry to bother you again. If you get a minute, do you have any insight on @gotmikhail's issue?

**Comment by gotmikhail** [comment]
@janesconference @stephenplusplus 
I couldn't get the wildcard to work, but I did hard-code the origin and got that through w/ no `xhr` issues. I'm still having an issue with writing out the file successfully, getting a `200` back from the `PUT` request, the file is listed in Cloud Storage, `Content-Type` is correct, but unable to properly load the file. That may be fully on our side.

**Comment by janesconference** [comment]
@gotmikhail 

I never tried with the wildcard, but sure it's working for me with the correct origin.

For this to work on the client, though, you [have to set CORS in your target bucket appropriately](https://cloud.google.com/storage/docs/cross-origin).

You'll then be able to PUT your chunks on that address as multiple of 256k, get a 308 for each of them, then PUT the final one with a Content-Range end value, and get a 200. The process is described [here](https://cloud.google.com/storage/docs/json_api/v1/how-tos/upload) and it's quite tricky.
